# Generated by Django 4.0.3 on 2022-06-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default=100, max_length=10),
        ),
    ]
