# Generated by Django 4.0.3 on 2022-06-23 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability_date',
            old_name='availability_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='availability_date',
            old_name='availability_time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='availability_date',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reserved',
        ),
        migrations.CreateModel(
            name='resevedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('Date', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.availability_date')),
            ],
        ),
    ]
