# Generated by Django 4.0.3 on 2022-06-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0006_alter_availability_date_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resevedtable',
            old_name='Date',
            new_name='reserved_date',
        ),
    ]
